#!/bin/bash

# Add gitlab to hosts file
grep -q -F "$GIT_HOSTS" /etc/hosts  || echo $GIT_HOSTS >> /etc/hosts

# Export all env vars containing "_" to a file for use with cron jobs
printenv | grep \_ | sed 's/^\(.*\)$/export \1/g' | sed 's/=/=\"/' | sed 's/$/"/g' > /root/project_env.sh
chmod +x /root/project_env.sh

# Clone repo to container
git clone -b $GIT_BRANCH $GIT_REPO /usr/src/app

# Copy in post-merge script to run npm install
cat /post-merge >> /usr/src/app/.git/hooks/post-merge
chmod +x /usr/src/app/.git/hooks/post-merge

# Run npm install
npm run setup

# Import cron jobs
crontab /root/crons.conf

#start cron in the background
/usr/sbin/cron -f &

# Start node server server.js
pm2 start --no-daemon $NODE_START --watch
