#!/bin/bash

# Add gitlab to hosts file
grep -q -F "$GIT_HOSTS" /etc/hosts  || echo $GIT_HOSTS >> /etc/hosts

# Clone repo to container
git clone -b $GIT_BRANCH $GIT_REPO /usr/src/app

# Run npm install
npm install

# write ENV to file
env > /root/env.txt

#start cron in the background
/usr/sbin/cron -f
